// elementos da página para executar as ações

const test = {
    make:'#make',
    model:'#model',
    cylinder:'#cylindercapacity',
    engine:'#engineperformance',
    date:'#dateofmanufacture',
    numberSeats: '#numberofseats',
    rightHdrive:':nth-child(7) > .group > :nth-child(1)',
    numberSeatsMotorcycle:'#numberofseatsmotorcycle',
    fuelType:'#fuel',
    payload:'#payload',
    totalWeight:'#totalweight',
    listPrice:'#listprice',
    licensePlateNumber:'#licenseplatenumber',
    annualMileage:'#annualmileage',
    buttonNextFirst:'#nextenterinsurantdata',
    firstName:'#firstname',
    lastName:'#lastname',
    birthDate:'#birthdate',
    gender:':nth-child(4) > .group > :nth-child(2) > .ideal-radio',
    streetAdress:'#streetaddress',
    country:'#country',
    zipCode:'#zipcode',
    city:'#city',
    occupation:'#occupation',
    hobbiesSpeeding:'section[style="display: block;"] > .idealforms-field-checkbox > .group > :nth-child(1) > .ideal-check',
    website:'#website',
    pictureOpen:'input[type=file]',
    buttonNextSecond:'#nextenterproductdata',
    startDate:'#startdate',
    insuranceSum:'#insurancesum',
    meritRating:'#meritrating', 
    damageInsurance:'#damageinsurance',
    opitionalProductsEuroProtection:'section[style="display: block;"] > .idealforms-field-checkbox > .group > :nth-child(1)',
    courtesyCar:'#courtesycar',
    buttonNextThird:'#nextselectpriceoption',
    selectOptionGold:':nth-child(3) > .ideal-radio',
    buttonNextFourth:'#nextsendquote',
    email:'#email',
    phone:'#phone',
    username:'#username',
    password:'#password',
    confirmPassword:'#confirmpassword',
    comments:'#Comments',
    buttonSend:'#sendemail',
    buttonOk:'.confirm'
}

export default test;